# yaml 配置
version: "3.7"
services:
  mysql8019:
    image: "mysql:8.0.19"
    ports:
      - "3306:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root123456@"
      MYSQL_DATABASE: "go_db"
      MYSQL_PASSWORD: "root123456@"
    volumes:
      - ./init.sql:/data/application/init.sql
  redis507:
      image: "redis:5.0.7"
      ports:
        - "6379:6379"
      command: redis-server --requirepass "ms.it@sun^"
      volumes:
        - ./data:/data
  web_app:
    build: .
    command: sh -c "./wait-for.sh mysql8019:3306 redis507:6379 -- ./app ./conf/config.yaml"
    depends_on:
      - mysql8019
      - redis507
    ports:
      - "8888:8081"