name: "web_app"
mode: "dev"
port: 8081
version: "v1.0.1"
start_time: "2022-01-01"
machine_id: 1
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: mysql8019
  port: 3306
  user: "root"
  password: "root123456@"
  dbname: "go_db"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: redis507
  port: 6379
  password: "ms.it@sun^"
  pool_size: 100
  db: 0
